# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 05:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('frc', models.IntegerField()),
                ('sta', models.IntegerField()),
                ('agi', models.IntegerField()),
                ('wit', models.IntegerField()),
                ('per', models.IntegerField()),
                ('lck', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('frc_bns', models.IntegerField()),
                ('sta_bns', models.IntegerField()),
                ('agi_bns', models.IntegerField()),
                ('wit_bns', models.IntegerField()),
                ('per_bns', models.IntegerField()),
                ('lck_bns', models.IntegerField()),
                ('dass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.Dass')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('frc', models.IntegerField()),
                ('sta', models.IntegerField()),
                ('agi', models.IntegerField()),
                ('wit', models.IntegerField()),
                ('per', models.IntegerField()),
                ('lck', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='race',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.Race'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
